### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by wcshen** [weiyithu/LiDAR-Distillation#1]
hello,
where can i find the code about "Pseudo Low-beam Data Generation"  in this repo?

**Comment by zyrant** [comment]
hello, did you find the code about "Pseudo Low-beam Data Generation"?  I couldn't find it.

**Comment by wcshen** [comment]
pcdet-dataset-kitti-kitti_dataset.py

Line196-line222



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 06/12/2022 21:56 |
| To | ***@***.***> |
| Cc | wancheng ***@***.***>、State ***@***.***> |
| Subject | Re: [weiyithu/LiDAR-Distillation] about the code (Issue #1) |

hello, did you find the code about "Pseudo Low-beam Data Generation"? I couldn't find it.

**Comment by zyrant** [comment]
> 

thanks.
