### ISSUE TITLE
How to generate low-beam data？

### ISSUE THREAD

**Issue by yux326** [weiyithu/LiDAR-Distillation#8]
It is mentioned in the paper that we need pseudo low-beam data generated from high-beam ones. 
Does this project include the code to generate low-beam-data?

**Comment by yux326** [comment]
I found it. 
It‘s in kitti_dataset.py
function porcess-single_scene

**Comment by Petros626** [comment]
@yux326 great! Can I just use KITTI in OpenPCDet and set the low-beam value to got a new dataset?
